// Which icon an exercise gets: a drawn pictogram of the movement for gym exercises (bench press,
// squat, curl…) and a sport or activity icon for everything else (badminton, swimming, gardening…).
// Rules are checked in order on the exercise's English name; the first match wins.

type Rule = [RegExp, string];

const STRENGTH: Rule[] = [
  [/stretch|mobility|yoga|pose\b|foam roll|-smr\b|cat-?cow|child'?s pose|cobra|pigeon|circles|dislocat|hug a ball|jefferson curl/i, "stretch"],
  [/handstand|wall walk/i, "handstand"],
  [/front lever|back lever|planche|human flag|dragon flag/i, "hang"],
  [/slam|throw|toss|chest push|chest pass|scoop/i, "slam"],
  [/atlas|stone|keg|tyre flip|tire flip|log lift|sandbag (load|over|shoulder)/i, "deadlift"],
  [/butt kick|acceleration|start technique|wall drill|push-off|leap|sprint|shuffle|cone/i, "sprint"],
  [/drag\b|backward drag|forward drag/i, "sled"],
  [/inchworm|crab|beast|body saw|fallout/i, "plank"],
  [/pallof|cable (lift|chop)|wood ?chop|half-kneeling cable/i, "twist"],
  [/neck/i, "shrug"],
  [/wrist|forearm|finger|pronation|supination|radial|ulnar|reverse plate curl/i, "wrist"],
  [/deadlift/i, "deadlift"],
  [/shrug/i, "shrug"],
  [/front squat/i, "frontSquat"],
  [/box squat/i, "squat"],
  [/mountain climber/i, "climber"],
  [/battl\w* ropes?/i, "battleRopes"],
  [/sled|prowler/i, "sled"],
  [/farmer|carry|suitcase|yoke|waiter walk/i, "carry"],
  [/snatch|clean|jerk|thruster|wall ball|overhead squat/i, "olympic"],
  [/swing|turkish get|get-?up/i, "kbSwing"],
  [/burpee|jump|\bhops?\b|bound|plyo|skater|jumping jack|plank jack|\bjacks\b|box (jump|skip)|man maker|sprawl/i, "jump"],
  [/face pull|reverse fl|rear delt|band pull-?apart|pull-?apart/i, "facePull"],
  [/fly\b|flye|flys|pec deck|crossover|cross-?over/i, "fly"],
  [/triceps? extension/i, "triceps"],
  [/incline (bench|press|dumbbell|barbell|smith|chest)|incline.*press/i, "incline"],
  [/bench press|floor press|chest press|press-?around|svend|guillotine|board press|pin press|spoto|close-?grip press|smith machine press|dumbbell press(?!.*shoulder)|decline (bench|press|dumbbell)/i, "bench"],
  [/push-?up|press-?up/i, "pushup"],
  [/\bdips?\b/i, "dip"],
  [/fly\b|flye|flys|pec deck|crossover|cross-?over/i, "fly"],
  [/muscle[- ]?up|pull[- ]?ups?\b|chin[- ]?ups?\b|chins?\b/i, "pullup"],
  [/hang\b|hanging (?!leg|knee)|dead hang|scapular/i, "hang"],
  [/pulldown|pull-?down|pullover|straight-?arm/i, "pulldown"],
  [/upright.*row|shrug/i, "shrug"],
  [/\brows?\b|rowing/i, "row"],
  [/hip thrust|glute bridge|bridge|frog pump/i, "bridge"],
  [/back extension|hyperextension|superman|reverse hyper/i, "superman"],
  [/deadlift|\brdl\b|good morning|rack pull|stiff[- ]leg|hip hinge|pull-?through/i, "deadlift"],
  [/leg press|hack squat|pendulum squat|belt squat/i, "legPress"],
  [/goblet|front squat|zercher|cossack/i, "frontSquat"],
  [/lunge|split squat|step-?up|step-?down|bulgarian|curtsy/i, "lunge"],
  [/squat|pistol|wall sit|sissy/i, "squat"],
  [/leg extension|leg curl|hamstring curl|nordic|glute-?ham/i, "legMachine"],
  [/calf|calves|heel raise|tibialis|toe raise/i, "calf"],
  [/abduct|adduct|clam|fire hydrant|side-?lying|lateral leg|glute kickback|donkey kick/i, "hipAbduct"],
  [/pushdown|push-?down|press-?down/i, "pushdown"],
  [/tricep|skull|french press|jm press|kickback|overhead extension|close-?grip/i, "triceps"],
  [/curl|chin.*bicep|bicep/i, "curl"],
  [/grip|pinch|plate hold|towel hang/i, "carry"],
  [/front.*raise|raise.*front|plate raise|front deltoid/i, "frontRaise"],
  [/raise|scaption|iron cross|y-t-w|lateral/i, "lateralRaise"],
  [/press|handstand|pike|landmine|arnold|military|push press/i, "ohp"],
  [/plank|bird dog|dead bug|hollow|l-sit|ab wheel|rollout|bear crawl|bear|crawl|stir the pot/i, "plank"],
  [/leg raise|knee raise|toes to bar|toes-to-bar|flutter|scissor|knees to/i, "legRaise"],
  [/twist|woodchop|wood chop|rotation|pallof|oblique|side bend|windmill|russian/i, "twist"],
  [/crunch|sit-?up|v-?up|jackknife|toe touch|tuck|ab\b|abs\b/i, "crunch"],
];

/** When no rule matches a strength exercise, its muscle group decides. */
const STRENGTH_FALLBACK: Record<string, string> = {
  Chest: "bench",
  Back: "row",
  Shoulders: "ohp",
  Arms: "curl",
  Legs: "squat",
  Core: "crunch",
  "Full Body": "kbSwing",
};

const ACTIVITY: Rule[] = [
  // Racket and ball sports
  [/badminton|chapteh|shuttlecock/i, "badminton"],
  [/table tennis|ping pong|pickleball|padel/i, "pingPong"],
  [/squash|racquetball/i, "squash"],
  [/tennis/i, "tennis"],
  [/sepak|takraw|footbag|kick-?ups/i, "takraw"],
  [/american football|touch \/ flag|australian rules|gaelic/i, "americanFootball"],
  [/futsal|football|soccer/i, "soccer"],
  [/basketball/i, "basketball"],
  [/water polo|underwater hockey|kayak polo/i, "waterPolo"],
  [/volleyball/i, "volleyball"],
  [/netball|handball|dodgeball/i, "handball"],
  [/ice hockey/i, "iceHockey"],
  [/hockey|lacrosse|hurling/i, "hockey"],
  [/rugby/i, "rugby"],
  [/cricket/i, "cricket"],
  [/baseball|softball/i, "baseball"],
  [/golf/i, "golf"],
  [/bowl/i, "bowling"],
  [/frisbee|disc golf/i, "frisbee"],
  [/kabaddi/i, "kabaddi"],
  [/billiard|snooker|pool table/i, "billiards"],
  [/dart/i, "darts"],
  [/archery|hunting/i, "archery"],
  [/fencing|kendo|sword/i, "fencing"],
  [/gymnastic|trampolin|rebound|acrobat|aerial|pole fitness|parkour|animal flow/i, "gymnastics"],
  [/gasing|top spinning/i, "top"],
  [/congkak|board game/i, "boardGame"],
  // Combat
  [/heavy bag|bag work|punching bag/i, "punchingBag"],
  [/shadow boxing/i, "punch"],
  [/kickbox|muay thai|body combat|cardio kickboxing/i, "kick"],
  [/boxing|sparring|bout|pad work|mitts/i, "boxing"],
  [/judo|jiu-?jitsu|wrestl|sambo|aikido|mma|krav|grapp|clinch/i, "wrestling"],
  [/karate|taekwondo|kung fu|wushu|hapkido|wing chun|silat|capoeira|self-defence|martial/i, "martialArts"],
  // Mind & body
  [/meditation|pranayama|nidra|breathing/i, "meditation"],
  [/tai chi|qigong|baduanjin|zhan zhuang/i, "taiChi"],
  [/yoga/i, "yoga"],
  [/pilates|barre|body balance/i, "pilates"],
  [/stretch|mobility|foam roll|physio|rehab|warm-up/i, "stretching"],
  // Dance
  [/lion dance|dragon dance|kuda kepang/i, "lionDance"],
  [/ballet/i, "ballet"],
  [/danc|zumba|tango|salsa|swing \/ lindy|bachata|flamenco|zapin|joget|inang|dikir|poco|senamrobik|hip hop|k-pop|breakdanc|cheer/i, "dance"],
  // Water
  [/scuba|snorkel|free diving/i, "scuba"],
  [/springboard|platform diving|diving/i, "diving"],
  [/kitesurf/i, "kitesurf"],
  [/surf|bodyboard|windsurf|wakeboard|water ski/i, "surf"],
  [/sail/i, "sailing"],
  [/kayak|canoe|paddleboard|raft|canyoning|outrigger/i, "kayak"],
  [/dragon boat|rowing a boat|crew|sculling|sampan/i, "rowing"],
  [/jet ski/i, "jetSki"],
  [/aqua|water aerobics|treading water|playing in the pool|water \(waist/i, "pool"],
  [/swim|lap|stroke|butterfly|medley|kickboard|pull buoy|fins|lifesaving|masters/i, "swim"],
  // Snow, ice, wheels
  [/snowboard/i, "snowboard"],
  [/snowshoe/i, "snowshoe"],
  [/cross-country ski|ski touring|skimo/i, "nordicSki"],
  [/ski erg/i, "skiErg"],
  [/ski/i, "ski"],
  [/ice skating|speed skating/i, "iceSkate"],
  [/roller|inline|blading|^skating$/i, "rollerSkate"],
  [/skateboard/i, "skateboard"],
  [/scooter/i, "scooter"],
  [/horse/i, "horse"],
  [/wheelchair/i, "wheelchair"],
  // Cycling
  [/e-bike|pedal assist/i, "eBike"],
  [/mountain bik|bmx|gravel|cyclocross|downhill \/ enduro/i, "mountainBike"],
  [/stationary|spin|indoor smart|recumbent|bike erg|assault|air bike|arm crank|arm bike|ergometer|hand cycling/i, "spinBike"],
  [/cycl|bicycl|unicycl|tandem|velodrome|bike/i, "bike"],
  // Gym machines & conditioning
  [/rowing machine|rowing, stationary|rower|row erg/i, "rowErg"],
  [/elliptical|arc trainer/i, "elliptical"],
  [/stair|step mill|stepmill|versaclimber|jacob'?s ladder|step-ups|step aerobics/i, "stairs"],
  [/treadmill|curved/i, "treadmill"],
  [/jump rope|rope jumping|skipping|double-unders/i, "jumpRope"],
  [/battle rope/i, "battleRopes"],
  [/rope climb/i, "ropeClimb"],
  [/sled|prowler/i, "sled"],
  [/kettlebell/i, "kbSwing"],
  [/burpee|jumping jack|calisthenics|hiit|tabata|emom|circuit|bootcamp|crossfit|hyrox|f45|grit|metcon|body attack|body pump|agility|\bocr\b|obstacle/i, "jump"],
  [/trx|suspension/i, "row"],
  [/video game|vr fitness|ring fit|beat saber|switch sports|wii/i, "videoGame"],
  [/aerobic|step|chair|senior|prenatal/i, "aerobics"],
  // Outdoors
  [/rock climbing|bouldering|climbing|via ferrata|abseil|rappel/i, "climbing"],
  [/mountaineering|kinabalu/i, "mountain"],
  [/nordic walking/i, "nordicWalk"],
  [/hik|trek|backpack|ruck|jungle/i, "hiking"],
  [/fishing/i, "fishing"],
  [/orienteering|geocach/i, "compass"],
  [/paraglid|kite flying|wau/i, "kite"],
  [/caving|spelunk/i, "caving"],
  // Everyday life
  [/stroller|pram/i, "stroller"],
  [/dog/i, "dog"],
  [/child|kids|swing/i, "child"],
  [/vacuum/i, "vacuum"],
  [/mop|sweep|scrub|clean|gotong/i, "cleaning"],
  [/window/i, "window"],
  [/mow|lawn|rak/i, "mowing"],
  [/garden|weed|plant|prun|hedge|compost|harvest|rubber tapping|farm|hoe/i, "gardening"],
  [/dig|shovel|drain|gutter/i, "shovel"],
  [/groceries|grocery|shopping|mall|pasar|trolley/i, "shopping"],
  [/furniture|boxes|packing|warehouse|stacking|moving house/i, "boxes"],
  [/car\b|motorbike|car repair|maintenance/i, "car"],
  [/carpentry|diy|construction|painting/i, "tools"],
  [/cook|kenduri|feast|sambal|food prep/i, "cooking"],
  [/dishes/i, "dishes"],
  [/laundry|ironing|clothes|beds|linen/i, "laundry"],
  [/standing desk|desk/i, "desk"],
  [/delivery/i, "delivery"],
  [/nursing|caregiving|patient/i, "caregiving"],
  [/retail|restaurant|waiting tables/i, "store"],
  // Running & walking last: many names above include "walking" or "running"
  [/sprint|shuttle run|beep test|track interval|400 m|fartlek|hill repeat/i, "sprint"],
  [/trail run|cross-country run|mountain/i, "trailRun"],
  [/run|jog|marathon|parkrun|tempo|recovery jog/i, "run"],
  [/walk|stroll|pok[eé]mon|race walking/i, "walk"],
];

const ACTIVITY_FALLBACK: Record<string, string> = {
  Walking: "walk",
  Running: "run",
  Cycling: "bike",
  "Gym Cardio": "jump",
  Combat: "martialArts",
  Classes: "aerobics",
  Swimming: "swim",
  Sports: "trophy",
  Everyday: "house",
  "Mind & Body": "yoga",
  "Water Sports": "kayak",
  Outdoor: "hiking",
  "Racket Sports": "tennis",
  Dance: "dance",
};

/** The icon key for an exercise. Gym movements get a pictogram key, everything else an activity key. */
export function exerciseIconKey(e: { name: string; kind: "strength" | "cardio"; category: string; met?: number }): string {
  const rules = e.kind === "strength" ? STRENGTH : ACTIVITY;
  for (const [re, key] of rules) if (re.test(e.name)) return key;
  // Stretches imported without "stretch" in the name ("90/90 Hamstring", "Lying Glute") have the stretching intensity.
  if (e.kind === "strength" && e.met !== undefined && e.met <= 2.5) return "stretch";
  // A cardio activity that names a lift ("Kettlebell swings / circuit") gets the lift's pictogram.
  if (e.kind === "cardio") for (const [re, key] of STRENGTH) if (re.test(e.name)) return key;
  return (e.kind === "strength" ? STRENGTH_FALLBACK : ACTIVITY_FALLBACK)[e.category] ?? (e.kind === "strength" ? "kbSwing" : "trophy");
}
